spring:
  datasource:
    url: ${AUDIT_LOG_DB_URL}
    username: ${AUDIT_LOG_DB_USERNAME}
    password: ${AUDIT_LOG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUDIT_LOG_OIDC_ISSUER}

server:
  forward-headers-strategy: framework

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

audit:
  security:
    require-https: true
